export const AUTH_DATA_CHANGE = 'AUTH_DATA_CHANGE';
export const AUTH_LOGIN = 'AUTH_LOGIN';

export const SETTINGS_DATA_CHANGE = 'SETTINGS_DATA_CHANGE';

export const EVENT_CREATE = 'EVENT_CREATE';
export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS';
export const EVENT_CREATE_ERROR = 'EVENT_CREATE_ERROR';
